apiVersion: batch/v1
kind: Job
metadata:
  name: wc-client
  labels:
    app: wc-client
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: ebr41nd/wc-client
        name: wc-client
        args:
        - http://redhat.com/en/technologies #Change this value to crawl another website
        env:
        - name: WC_SERVER_HOST
          value: http://wc-server #Change this value to match where the wc-server is deployed